### Result based on 100 Results - **Version 2.3.2**

Input File:     **matches+suggestion_100.csv**
<br> Output File:    **Data.xlsx**

In [1]:
import pandas as pd

# Load Excel file into a pandas DataFrame
excel_file = r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\Data.xlsx'
master = pd.read_excel(excel_file)

# Load CSV file into another pandas DataFrame
csv_file = r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestion_100.csv'
ms = pd.read_csv(csv_file)

#### Handling Matches+Suggestion

In [2]:
ms.head()

,MANUFACTURE,BRAND,ITEMDESC,QTY,UNIT,PACKSIZE,PACKTYPE,MATCHED,RESULT,nitemcode,company,brand,itemdesc,qty,uomdesc,pack_size,packaging,ERROR,ProductName,Suggestion
0,SMITHKLINE BEECHAM (PVT) LTD,SENSODYNE,SENSODYNE SOFT 1 NO SAVE 95/=,1,NO,1 NO,BRUSH,1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUFACTURE,NaN,63964.0
1,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA/ PLPCH/ 100GM,100,GM,100GM,PLPCH,1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUFACTURE,NaN,NaN
2,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA /PLPCH /50GM,50,GM,50GM,PLPCH,1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUFACTURE,NaN,NaN
3,UNILEVER SRI LANKA LTD,SUNSILK,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO WITH ...,80,ML,80 ML,PLBOT,0,2.0,63972.0,UNILEVER SRI LANKA LTD,SUNSILK,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO 5 NAT...,80.0,ML,80.00 ML,PLBOT,NaN,1. SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO\n ...,NaN
4,FREELAN ENTERPRISES,FREELAN,FREELAN MALDIVE FISH FLAVOUR 70 GM SAVE 10/=,70,GM,70 GM,PLPCH,0,2.0,34284.0,FREELAN ENTERPRISES,FREELAN,FREELAN MALDIVE FISH FLAVOUR 70 GM,70.0,GM,70.00 GM,PLPCH,NaN,Freelan Maldivian Fish Flavor,NaN

In [3]:
ms = ms[['MATCHED', 'nitemcode', 'Suggestion']]
ms.head()

   MATCHED  nitemcode  Suggestion
0        1        NaN     63964.0
1        1        NaN         NaN
2        1        NaN         NaN
3        0    63972.0         NaN
4        0    34284.0         NaN

In [4]:
ms = ms.fillna(9)
ms = ms.apply(lambda col: col.astype(int) if pd.api.types.is_numeric_dtype(col) and (col.dropna() % 1 == 0).all() else col)

ms.head()

   MATCHED  nitemcode  Suggestion
0        1          9       63964
1        1          9           9
2        1          9           9
3        0      63972           9
4        0      34284           9

In [5]:
ms.to_csv(r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestion1.csv', index=False)

#### Handling Master

In [6]:
master.head()

,PERIOD,AUDITTYPE,STORECODE,DLRCODE,ITEMCODE,CATEGORY,MANUFACTURE,BRAND,ITEMDESC,MRP,...,Matched: ITEMDESC,Matched: BRAND,Matched: MANUFACTURE,Matched: PACKTYPE,Matched: PACKSIZE,Reason,Suggestion,Score,Datacore Matching,Datacore Matching Details
0,202410,1,120547179,10946010003,1730008019565,14,SMITHKLINE BEECHAM (PVT) LTD,SENSODYNE,SENSODYNE SOFT 1 NO SAVE 95/=,195,...,NaN,NaN,NaN,NaN,NaN,Target Company not found| Target Brand not fou...,NaN,NaN,Wrong,Wrong No Match
1,202410,1,133670987,19354010001,1729584139818,12,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA/ PLPCH/ 100GM,290,...,NaN,NaN,DAINTEE MARKETING,NaN,NaN,| Target Brand not found| Target Packtype not ...,NaN,NaN,Correct,Correct No Match
2,202410,1,133670987,19354010001,1729584017998,12,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA /PLPCH /50GM,155,...,NaN,NaN,DAINTEE MARKETING,NaN,NaN,| Target Brand not found| Target Packtype not ...,NaN,NaN,Correct,Correct No Match
3,202410,1,53951366,10006010001,1729575545353,26,UNILEVER SRI LANKA LTD,SUNSILK,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO WITH ...,340,...,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO WITH ...,SUNSILK,UNILEVER SRI LANKA LTD,PLBOT,80.00 ML,NaN,EMF,0.964578,Wrong,Wrong Match
4,202410,1,53951366,10006010001,1729572854804,10,FREELAN ENTERPRISES,FREELAN,FREELAN MALDIVE FISH FLAVOUR 70 GM SAVE 10/=,150,...,FREELAN MALDIVE FISH FLAVOUR 70 GM,FREELAN,FREELAN ENTERPRISES,PLPCH,70.00 GM,NaN,EMF,0.963639,Correct,Correct Match

In [7]:
master = master['NITEMCODE']
master.head()

0    63964
1        9
2        9
3    63972
4    34284
Name: NITEMCODE, dtype: int64

In [8]:
master.to_csv(r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\master1.csv', index=False)

#### Matching

In [9]:
import pandas as pd

def analyze_dataframes(ms, master):
    """
    Analyzes two DataFrames to find matching values and calculate metrics.

    Args:
        ms (pd.DataFrame): DataFrame with 'nitemcode' and 'Suggestion' columns.
        master (pd.DataFrame): DataFrame with a single column (name doesn't matter).

    Returns:
        None. Prints the calculated metrics.
    """

    # 1. Find matching values in the same row
    matches = []
    for i in range(len(master)):
        master_value = master.iloc[i, 0]  # Get value from master DataFrame
        if (ms.iloc[i]['nitemcode'] == master_value) or (ms.iloc[i]['Suggestion'] == master_value):
            matches.append(True)
        else:
            matches.append(False)

    # Calculate metrics for all rows
    true_count = matches.count(True)
    false_count = matches.count(False)
    total_count = len(matches)

    true_percentage = (true_count / total_count) * 100 if total_count > 0 else 0
    false_percentage = (false_count / total_count) * 100 if total_count > 0 else 0

    print("Overall Matching Metrics:")
    print(f"True Matches: {true_count} ({true_percentage:.2f}%)")
    print(f"False Matches: {false_count} ({false_percentage:.2f}%)")

    # 2. Analyze rows containing '9'
    nine_matches = []
    for i in range(len(master)):
        master_value = master.iloc[i, 0]
        if master_value == 9:
            if (ms.iloc[i]['nitemcode'] == 9) or (ms.iloc[i]['Suggestion'] == 9):
                nine_matches.append(True)
            else:
                nine_matches.append(False)

    true_nine_count = nine_matches.count(True)
    false_nine_count = nine_matches.count(False)
    total_nine_count = len(nine_matches)

    true_nine_percentage = (true_nine_count / total_nine_count) * 100 if total_nine_count > 0 else 0
    false_nine_percentage = (false_nine_count / total_nine_count) * 100 if total_nine_count > 0 else 0

    print("\nMetrics for Rows Containing '9':")
    print(f"True '9' Matches: {true_nine_count} ({true_nine_percentage:.2f}%)")
    print(f"False '9' Matches: {false_nine_count} ({false_nine_percentage:.2f}%)")

ms = pd.read_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestion1.csv")  # Replace with your actual file path
master = pd.read_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\master1.csv")  # Replace with your actual file path

# Crop master DataFrame
ms_len = len(ms)
master = master.iloc[:ms_len]

analyze_dataframes(ms, master)

Overall Matching Metrics:
True Matches: 90 (90.00%)
False Matches: 10 (10.00%)

Metrics for Rows Containing '9':
True '9' Matches: 22 (100.00%)
False '9' Matches: 0 (0.00%)

### Result based on Full Results - **Version 2.3.2**

Input File:     **matches+suggestion_full.csv**
<br> Output File:    **Data.xlsx**

In [11]:
import pandas as pd

# Load Excel file into a pandas DataFrame
excel_file = r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\Data.xlsx'
master = pd.read_excel(excel_file)

# Load CSV file into another pandas DataFrame
csv_file = r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestions_full.csv'
ms = pd.read_csv(csv_file)

#### Handling Matches+Suggestion

In [12]:
ms.head()

,MANUFACTURE,BRAND,ITEMDESC,QTY,UNIT,PACKSIZE,PACKTYPE,MATCHED,nitemcode,company,brand,itemdesc,qty,uomdesc,pack_size,packaging,ERROR,ProductName,Suggestion
0,SMITHKLINE BEECHAM (PVT) LTD,SENSODYNE,SENSODYNE SOFT 1 NO SAVE 95/=,1.0,NO,1 NO,BRUSH,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUFACTURE,NaN,63964.0
1,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA/ PLPCH/ 100GM,100.0,GM,100GM,PLPCH,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUFACTURE,NaN,NaN
2,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA /PLPCH /50GM,50.0,GM,50GM,PLPCH,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MANUFACTURE,NaN,NaN
3,UNILEVER SRI LANKA LTD,SUNSILK,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO WITH ...,80.0,ML,80 ML,PLBOT,0,63972.0,UNILEVER SRI LANKA LTD,SUNSILK,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO 5 NAT...,80.0,ML,80.00 ML,PLBOT,NaN,1. SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO\n ...,NaN
4,FREELAN ENTERPRISES,FREELAN,FREELAN MALDIVE FISH FLAVOUR 70 GM SAVE 10/=,70.0,GM,70 GM,PLPCH,0,34284.0,FREELAN ENTERPRISES,FREELAN,FREELAN MALDIVE FISH FLAVOUR 70 GM,70.0,GM,70.00 GM,PLPCH,NaN,Freelan Maldivian Fish Flavor,NaN

In [13]:
ms = ms[['MATCHED', 'nitemcode', 'Suggestion']]
ms.head()

   MATCHED  nitemcode  Suggestion
0        1        NaN     63964.0
1        1        NaN         NaN
2        1        NaN         NaN
3        0    63972.0         NaN
4        0    34284.0         NaN

In [14]:
ms = ms.fillna(9)
ms = ms.apply(lambda col: col.astype(int) if pd.api.types.is_numeric_dtype(col) and (col.dropna() % 1 == 0).all() else col)

ms.head()

   MATCHED  nitemcode  Suggestion
0        1          9       63964
1        1          9           9
2        1          9           9
3        0      63972           9
4        0      34284           9

In [15]:
ms.to_csv(r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestion2.csv', index=False)

#### Handling Master

In [16]:
master.head()

,PERIOD,AUDITTYPE,STORECODE,DLRCODE,ITEMCODE,CATEGORY,MANUFACTURE,BRAND,ITEMDESC,MRP,...,Matched: ITEMDESC,Matched: BRAND,Matched: MANUFACTURE,Matched: PACKTYPE,Matched: PACKSIZE,Reason,Suggestion,Score,Datacore Matching,Datacore Matching Details
0,202410,1,120547179,10946010003,1730008019565,14,SMITHKLINE BEECHAM (PVT) LTD,SENSODYNE,SENSODYNE SOFT 1 NO SAVE 95/=,195,...,NaN,NaN,NaN,NaN,NaN,Target Company not found| Target Brand not fou...,NaN,NaN,Wrong,Wrong No Match
1,202410,1,133670987,19354010001,1729584139818,12,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA/ PLPCH/ 100GM,290,...,NaN,NaN,DAINTEE MARKETING,NaN,NaN,| Target Brand not found| Target Packtype not ...,NaN,NaN,Correct,Correct No Match
2,202410,1,133670987,19354010001,1729584017998,12,IDEA AFFIX MARKETING,IDEA TEA,IDEA TEA /PLPCH /50GM,155,...,NaN,NaN,DAINTEE MARKETING,NaN,NaN,| Target Brand not found| Target Packtype not ...,NaN,NaN,Correct,Correct No Match
3,202410,1,53951366,10006010001,1729575545353,26,UNILEVER SRI LANKA LTD,SUNSILK,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO WITH ...,340,...,SUNSILK NOURISHING SOFT & SMOOTH SHAMPOO WITH ...,SUNSILK,UNILEVER SRI LANKA LTD,PLBOT,80.00 ML,NaN,EMF,0.964578,Wrong,Wrong Match
4,202410,1,53951366,10006010001,1729572854804,10,FREELAN ENTERPRISES,FREELAN,FREELAN MALDIVE FISH FLAVOUR 70 GM SAVE 10/=,150,...,FREELAN MALDIVE FISH FLAVOUR 70 GM,FREELAN,FREELAN ENTERPRISES,PLPCH,70.00 GM,NaN,EMF,0.963639,Correct,Correct Match

In [17]:
master = master['NITEMCODE']
master.head()

0    63964
1        9
2        9
3    63972
4    34284
Name: NITEMCODE, dtype: int64

In [18]:
master.to_csv(r'D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\master2.csv', index=False)

#### Matching

In [19]:
import pandas as pd

def analyze_dataframes(ms, master):
    """
    Analyzes two DataFrames to find matching values and calculate metrics.

    Args:
        ms (pd.DataFrame): DataFrame with 'nitemcode' and 'Suggestion' columns.
        master (pd.DataFrame): DataFrame with a single column (name doesn't matter).

    Returns:
        None. Prints the calculated metrics.
    """

    # 1. Find matching values in the same row
    matches = []
    for i in range(len(master)):
        master_value = master.iloc[i, 0]  # Get value from master DataFrame
        if (ms.iloc[i]['nitemcode'] == master_value) or (ms.iloc[i]['Suggestion'] == master_value):
            matches.append(True)
        else:
            matches.append(False)

    # Calculate metrics for all rows
    true_count = matches.count(True)
    false_count = matches.count(False)
    total_count = len(matches)

    true_percentage = (true_count / total_count) * 100 if total_count > 0 else 0
    false_percentage = (false_count / total_count) * 100 if total_count > 0 else 0

    print("Overall Matching Metrics:")
    print(f"True Matches: {true_count} ({true_percentage:.2f}%)")
    print(f"False Matches: {false_count} ({false_percentage:.2f}%)")

    # 2. Analyze rows containing '9'
    nine_matches = []
    for i in range(len(master)):
        master_value = master.iloc[i, 0]
        if master_value == 9:
            if (ms.iloc[i]['nitemcode'] == 9) or (ms.iloc[i]['Suggestion'] == 9):
                nine_matches.append(True)
            else:
                nine_matches.append(False)

    true_nine_count = nine_matches.count(True)
    false_nine_count = nine_matches.count(False)
    total_nine_count = len(nine_matches)

    true_nine_percentage = (true_nine_count / total_nine_count) * 100 if total_nine_count > 0 else 0
    false_nine_percentage = (false_nine_count / total_nine_count) * 100 if total_nine_count > 0 else 0

    print("\nMetrics for Rows Containing '9':")
    print(f"True '9' Matches: {true_nine_count} ({true_nine_percentage:.2f}%)")
    print(f"False '9' Matches: {false_nine_count} ({false_nine_percentage:.2f}%)")

ms = pd.read_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestion2.csv")  # Replace with your actual file path
master = pd.read_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\master2.csv")  # Replace with your actual file path

# Crop master DataFrame
ms_len = len(ms)
master = master.iloc[:ms_len]

analyze_dataframes(ms, master)

Overall Matching Metrics:
True Matches: 749 (72.16%)
False Matches: 289 (27.84%)

Metrics for Rows Containing '9':
True '9' Matches: 269 (100.00%)
False '9' Matches: 0 (0.00%)

### Surfing the **Complete Results**

In [20]:
import pandas as pd

def analyze_dataframes(ms, master):
    """
    Analyzes two DataFrames to find matching values and calculate metrics.
    Concatenates the DataFrames and adds a flag column for true and false matches.

    Args:
        ms (pd.DataFrame): DataFrame with 'nitemcode' and 'Suggestion' columns.
        master (pd.DataFrame): DataFrame with a single column (name doesn't matter).

    Returns:
        pd.DataFrame: Concatenated DataFrame with a flag column indicating matches.
    """

    # 1. Find matching values in the same row
    matches = []
    flags = []
    for i in range(len(master)):
        master_value = master.iloc[i, 0]  # Get value from master DataFrame
        if (ms.iloc[i]['nitemcode'] == master_value) or (ms.iloc[i]['Suggestion'] == master_value):
            matches.append(True)
            flags.append(0)  # True match flag
        else:
            matches.append(False)
            flags.append(1)  # False match flag

    # Calculate metrics for all rows
    true_count = matches.count(True)
    false_count = matches.count(False)
    total_count = len(matches)

    true_percentage = (true_count / total_count) * 100 if total_count > 0 else 0
    false_percentage = (false_count / total_count) * 100 if total_count > 0 else 0

    print("Overall Matching Metrics:")
    print(f"True Matches: {true_count} ({true_percentage:.2f}%)")
    print(f"False Matches: {false_count} ({false_percentage:.2f}%)")

    # 2. Concatenate DataFrames and add flag column
    concatenated_df = pd.concat([ms, master.reset_index(drop=True)], axis=1)
    concatenated_df['Match_Flag'] = flags

    return concatenated_df

# Assuming ms and master DataFrames are loaded from CSVs as in your original code
ms = pd.read_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\matches+suggestion2.csv")
master = pd.read_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\master2.csv")

# Crop master DataFrame
ms_len = len(ms)
master = master.iloc[:ms_len]

# Analyze and concatenate DataFrames
result_df = analyze_dataframes(ms, master)
result_df.to_csv(r"D:\Projects\SKU\StockKeepingUnit\Result_Verification\Version_2.3.2\concatenated_results.csv", index=False)

Overall Matching Metrics:
True Matches: 749 (72.16%)
False Matches: 289 (27.84%)